  - name: Install epoptes client through custom command
    command: apt-get -y install --install-recommends epoptes-client
    register: apt_install

  - name: Check if epoptes-client service exists
    service: name=epoptes-client
    register: service

  - name: Add default Epoptes SERVER value to /etc/default/epoptes-client
    when: service.status.LoadState == 'loaded'
    lineinfile:
      path: /etc/default/epoptes-client
      state: present
      regexp: '^SERVER=smx-HP-Compaq-8200-Elite-SFF-PC'
      line: 'SERVER=smx-HP-Compaq-8200-Elite-SFF-PC'

  - name: Add default Epoptes SERVER IP address and hostname to /etc/hosts
    when: service.status.LoadState == 'loaded'
    lineinfile:
      path: /etc/hosts
      state: present
      regexp: '^192.168.3.54 server smx-HP-Compaq-8200-Elite-SFF-PC'
      line: '192.168.3.54 server smx-HP-Compaq-8200-Elite-SFF-PC'

  - name: Fetch the OpenSSL certificate from the server
    when: service.status.LoadState == 'loaded'
    #command: cd && epoptes-client -c
    shell: cd && epoptes-client -c
    register: epoptes_fetch_SSL_cert
