  - name: Check if lightdm service exists (stat module)
    stat: path=/etc/init.d/lightdm
    register: service_stat2

  - name: Check if lightdm service exists (service module)
    service: name=lightdm
    register: service2

  - name: Start lightdm service if exists and is stopped
    service:
      name: lightdm
      state: started
    when: service_stat2.stat.exists and service2.status.SubState == 'dead'
    register: service_started
