---
- hosts: a23-alumnes
  become: yes

  tasks:
  - import_tasks: tasks/update_local_repositories_cache.yml
    when: "'a23' in ansible_hostname"
  - import_tasks: tasks/install_python_apt.yml
    when: "'a23' in ansible_hostname"
  - import_tasks: tasks/install_epoptes_client.yml
    when: "'a23' in ansible_hostname"
