---
- hosts: a27-alumnes
  become: yes
  vars_files:
    - data/install_packages.yml

  tasks:
  - import_tasks: tasks/update_local_repositories_cache.yml
  - import_tasks: tasks/install_packages.yml
  - import_tasks: tasks/install_packages_from_url.yml
